server:
  port: 8765

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      mvc:
        routes:
          - id: quiz-service
            uri: lb://QUIZ-SERVICE
            predicates:
              - Path=/quiz-service/**
            filters:
              - StripPrefix=1

          - id: question-service
            uri: lb://QUESTION-SERVICE
            predicates:
              - Path=/question-service/**
            filters:
              - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka